services:
  mysql:
    image: 'mysql:8.4'
    environment:
      - 'MYSQL_DATABASE=urijip'
      - 'MYSQL_USER=urijip'
      - 'MYSQL_PASSWORD=urijip'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'TZ=Asia/Seoul'
    ports:
      - '3306:3306'
    volumes:
      - 'mysql-data:/var/lib/mysql'

volumes:
  mysql-data:
